### PR TITLE
Wanderer patch 2a

### PR DESCRIPTION
**Pull request by rude9**

### CODE REVIEW

**Comment by wanderer** [comment]
what is this for?

**Comment by rude9** [comment]
🗺️

javed khan reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

**Comment by rude9** [comment]
🥷

javed khan reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

**Comment by rude9** [comment]
👫

javed khan reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

**Comment by rude9** [comment]
javed khan has sent you an email via Gmail confidential mode:

[image: Gmail logo]Re: [primea/design] Wanderer patch 2a (#10) <https://confidential-mail.google.com/msg/AJ05YhcVAErrw4KU3PHyESIVQdXYEguFra0WbrpQr3XrPmB4du6TEw422YZbFgA8A2ydri1n0cLM1JzIr5mmFndy_3D-n5xx-PgOloeURbh69Rwkm1mw3njDJb3Cc-JdjobB-rcFeUg7ZNy8rD2biVWgUOX20YT1BWAkTvprdvOaA9U949rhI8afNEipW2V2S298oH5btDxMbwGKNcqqqC1nUOUIlmax_O_3xG-itapMP7F2Xhw8lukZv9w7xT2Ufep1pa5rZIY=>

This message was sent on Sep 20, 2025 at 6:59:49 PM PDT
You can open it by clicking the link below. This link will only work for ***@***.***

View the email <https://confidential-mail.google.com/msg/AJ05YhcVAErrw4KU3PHyESIVQdXYEguFra0WbrpQr3XrPmB4du6TEw422YZbFgA8A2ydri1n0cLM1JzIr5mmFndy_3D-n5xx-PgOloeURbh69Rwkm1mw3njDJb3Cc-JdjobB-rcFeUg7ZNy8rD2biVWgUOX20YT1BWAkTvprdvOaA9U949rhI8afNEipW2V2S298oH5btDxMbwGKNcqqqC1nUOUIlmax_O_3xG-itapMP7F2Xhw8lukZv9w7xT2Ufep1pa5rZIY=>

Gmail confidential mode gives you more control over the messages you send. The sender may have chosen to set an expiration time, disable printing or forwarding, or track access to this message. Learn more <https://support.google.com/mail/answer/7674059>
Gmail: Email by Google
Use is subject to the Google Privacy Policy <https://myaccount.google.com/privacypolicy?hl=en>
Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
You have received this message because someone sent you an email via Gmail confidential mode.
[image: Google logo]

**Pull request closed without merging**
